### ISSUE TITLE
Missing git tag for 1.2.6 release

### ISSUE THREAD

**Issue by felixonmars** [tantale/deprecated#10]
It would be nice to keep PyPI releases and git tags in sync :)

**Comment by soxofaan** [comment]
Also: https://github.com/tantale/deprecated/releases currently shows 1.2.4 as "last release"

![Screenshot from 2019-07-18 11-16-24](https://user-images.githubusercontent.com/44946/61445417-a78b2200-a94d-11e9-9596-35639195cfbc.png)

**Comment by tantale** [comment]
Just push the missing tags, thanks for telling.
