### ISSUE TITLE
Packaging deprecated into Fedora

### ISSUE THREAD

**Issue by phracek** [tantale/deprecated#11]
It looks like this project is not packaged in Fedora.
Do you plan to package it into Fedora?
Do you think it would be possible to add Fedora RPM spec file into this repository?

We have a project https://packit.dev/, which would automate it a bit once here is a configuration file `.packit.yaml`
What do you think about it?

I would be glad for any kind of response.

**Comment by phracek** [comment]
PyGithub project depends on `deprecated`. It blocks releasing new PyGithub version into Fedora https://bugzilla.redhat.com/show_bug.cgi?id=1595244#c14

**Comment by tantale** [comment]
Great idea!

I have absolutely no idea on how to package the Deprecated Library in Fedora (or other OS). You may explain that to me. Just give some pointers on resources or tutorials.

You can create a pull request to add the Packit configuration file. But you’ll need to wait for the next release of this library.

I’m currently on Holliday. So, not really available for an important update.

**Comment by phracek** [comment]
Here is package review request for python-Deprecated (https://bugzilla.redhat.com/show_bug.cgi?id=1733508)

**Comment by tantale** [comment]
The review request is about Deprecated v1.2.6. I can add the `.packit.yaml` file only in the next version (v1.2.7). Is it a problem?

**Comment by phracek** [comment]
Of course not. `.packit.yaml` does not depend on the version. It is enough to be present in the upstream repository. I will let you know later on more details.

By the way thanks for collaboration.
