### ISSUE TITLE
please publish 1.2.7 release to conda

### ISSUE THREAD

**Issue by Tagar** [tantale/deprecated#14]
https://anaconda.org/conda-forge/deprecated

Latest version there is still 1.2.6

Please publish 1.2.7 release to conda

Thank you

**Comment by tantale** [comment]
This library is publish to the official [Python Package Index](https://pypi.org/project/Deprecated/#history), not directly to Conda.

I don't know who (what) is responsible to keep the Conda repository up-to-date. But it's not me.

**Comment by Tagar** [comment]
Thanks for prompt response @tantale 

conda recipe for `deprecated` is defined here 
https://github.com/conda-forge/deprecated-feedstock

cc @mariusvniekerk - please publish 1.2.7 release to conda

Thank you both!

**Comment by mariusvniekerk** [comment]
Landed the update in the conda-forge feedstock.  Feel free to add yourself as a maintainer if you'd like to help out on the packaging effort.

**Comment by tantale** [comment]
Ok to contribute (but I am not an anaconda user).

- I have created my "tantale" account in the [Anaconda Forge](https://anaconda.org/conda-forge),
- I have also install the anaconda-client (`pipx install anaconda-client`).

Just tell me how to add myself as a maintainer…

Curious : why using Anaconda Forge and not simply PyPi?

**Comment by Tagar** [comment]
- `conda` is better for environments that has complex dependencies, as pip sometimes doesn't resolve correctly requirements between cascade of dependencies. 
 - It's also much better for some python packages that do have native code (like cythonized libraries etc) - basically conda package is a ready to use distribution, while pip may trigger compiling through gcc etc.. 

The latter doesn't apply to `deprecated` as a it's a simple pure python package.

**Comment by tantale** [comment]
@Tagar, conda is probably a good product, but this doesn't answer my question : why having another Python package repository ? Why not using PyPi directly ?

**Comment by Tagar** [comment]
@tantale `conda` is a general package manager (although it is primarily used for python centric projects), while `pypi` is solely used for python packages. Their formats are not compatible. I hope that explains your question.
