### ISSUE TITLE
KeyError: 'adapter' when subclassing class that's deprecated

### ISSUE THREAD

**Issue by Fenkiou** [tantale/deprecated#2]
### Expected Behavior
Subclass a class that is marked as deprecated shouldn't raises an error.

### Actual Behavior

Subclassing a class that's deprecated raises a `TypeError`

```pytb
>>> from deprecated import deprecated
>>> @deprecated
... class MyClass: pass
...
>>> class MyOtherClass(MyClass): pass
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/alex/.virtualenvs/uptime-backend/lib/python3.6/site-packages/wrapt/decorators.py", line 128, in __init__
    adapter = kwargs.pop('adapter')
KeyError: 'adapter'
>>>

```

### Environment

* Python version: 3.6
* Deprecated version: 1.2.0

Sorry for the duplicate issue with https://github.com/vrcmarcos/python-deprecated/issues/7 but I saw that this is here that I should have opened the issue as the library was renamed.

**Comment by tantale** [comment]
Hi, weird error indeed. I need to diagnose more further.

**Comment by tantale** [comment]
The decorated (base-)class should be a class.

**Comment by Fenkiou** [comment]
Maybe some help: https://stackoverflow.com/questions/15155466/decorator-and-error-function-argument-1-must-be-code-not-str

It's the error I get when I use the other library but maybe it can help you

**Comment by Kentzo** [comment]
I recently had to deal with class deprecation while keeping the ability to instantiate, subclass and pass `isinstance` and `issubclass` checks.

Here is the solution I came with: https://stackoverflow.com/a/52087847/188530

It's written for Python 3.

**Comment by tantale** [comment]
Yes, this is the idea.

I think that the decorator should decorate the `__new__` method of the class, not the class itself (because it turns it into a function, which is not inheritable).

I have started the implementation and I’m still testing that. Stay tuned.

**Comment by Kentzo** [comment]
To pass subclass / isinstance you have to use a metaclass though. You cannot override `__instancecheck__` and `__subclasscheck__` otherwise.
