### ISSUE TITLE
Gentle plea for merging deprecation and deprecated packages

### ISSUE THREAD

**Issue by mcepl** [tantale/deprecated#31]
This just doesn’t make sense. Two tiny packages which do the same, both of them have to be packaged for all Linux/other distributions, all of them checked for security or whatever-else issues. Could you please guys join the effort?

Thank you.

Files also as https://github.com/briancurtin/deprecation/issues/51

**Comment by nkrot** [comment]
The problem with Python is that "there must be only one way to do things and this is the way I do them".
