### ISSUE TITLE
versionadded emit DeprecationWarning during pytest

### ISSUE THREAD

**Issue by rino0601** [tantale/deprecated#34]
According to the [this example](https://deprecated.readthedocs.io/en/latest/sphinx_deco.html#more-elaborate-example) `versionadded` should not emit the warning, but when I run the test code it does.

### Expected Behavior

```python
from deprecated.sphinx import versionadded

class Macros(object):
    
    class Macro(object):
        def __call__(self, *args,**kwargs):
            ... 

    @versionadded(version='0.7.0')
    class HiveDatabase(Macro):
        ...

```

I expected this will work fine

### Actual Behavior

when I run pytest...

```pytb
tests/context/test_macros.py: 12 tests with warnings
  /Users/user/IdeaProjects/airsflow/airsflow/context/macros.py:58: DeprecationWarning: Call to deprecated class HiveDatabase. -- Deprecated since version 0.7.0.
    return cls(ctx, *args, namespace=namespace, context=context, **kwargs)

```

### Environment

* Python version: 3.6.11
* Deprecated version: 1.2.10

**Comment by tantale** [comment]
Hello,

I confirm that this is an issue with `versionadded` and `versionchanged`.

The Sphinx adapter shouldn't call the base class wrapper for this kind of directives to avoid the warning.

Can you make a PR with an unit test (or fix the existing unit tests)?

Regards
