### ISSUE TITLE
TypeError in deprecated class because of arguments given to __new__

### ISSUE THREAD

**Issue by MatthiasKohl** [tantale/deprecated#4]
### Expected Behavior
No exception, returns class as expected.

```python
# Paste a minimal example that causes the problem.
@deprecated('kwargs class')
class ClassKwargs(object):
    def __init__(self, a=5):
        super(ClassKwargs, self).__init__()
        self.state = a

    def method(self):
        return self.state
        
ClassKwargs(6)
```

### Actual Behavior
Not complete traceback but most important part:

```pytb
    ClassKwargs(6)
  File "/home/matt/miniconda3/envs/df/lib/python3.5/site-packages/deprecated/classic.py", line 104, in wrapped_cls
    return old_new1(*args, **kwargs)
TypeError: object() takes no parameters
```

### Environment

* Python version: tested on 2.7, 3.5, 3.6, 3.7
* Deprecated version: 1.2.3

**Comment by MatthiasKohl** [comment]
I'm not sure if the underlying problem comes from this library, so I'm not sure if this is really the best place to report this bug. On my system at least, I found a weird issue, where if you use a function like this:

```python
def new_constructor(cls, *args, **kwargs):
  print(cls)
  print(args)
  print(kwargs)

SomeClass.__new__ = classmethod(new_constructor)
```

It seems to call the `new_constructor` with the class argument twice (in `cls` and `args[0]`). But doing this:

```python
def new_constructor(*args, **kwargs):
  print(cls)
  print(args)
  print(kwargs)

SomeClass.__new__ = classmethod(new_constructor)
```

works as expected.

No idea why, this looks very strange... possibly an obscure issue with my system (?)

**Comment by MatthiasKohl** [comment]
I ended up working around this problem by using deprecated on the `__init__` function only. Not sure what the underlying issue is, though.

**Comment by tantale** [comment]
I need to investigate this issue further.

**Comment by tantale** [comment]
This exception is raised when `__init__` takes some parameters (in addition to `self`).

**Comment by tantale** [comment]
Here is a demonstration of the problem:

```python
class Something(object):
    def __new__(cls, *args, **kwargs):
        return super(Something, cls).__new__(cls, *args, **kwargs)

    def __init__(self, a=5):
        self.a = a


Something(5)
```

You get:

```
Traceback (most recent call last):
  ...
TypeError: object() takes no parameters
```

Because `object.__new__` has no extra parameters.
