### ISSUE TITLE
Sphinx directives require version argument

### ISSUE THREAD

**Issue by auscompgeek** [tantale/deprecated#40]
The Sphinx [`versionadded`], `versionchanged`, and `deprecated` directives have a non-optional `version` argument. However, Deprecated will happily generate a Sphinx directive that is missing the version argument:

https://github.com/tantale/deprecated/blob/a02525b4f6e112743e1142fc9735dd4d46a4c66e/deprecated/sphinx.py#L100

[`versionadded`]: https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-versionadded

**Comment by tantale** [comment]
The Sphinx build shows a warning similar to:

```
reading sources... [100%] api                                                                                           
/Users/tantale/workspace/deprecated-demo-sphinx/src/deprecated_demo/sphinx/main.py:docstring of deprecated_demo.sphinx.main.add:7: WARNING: Error in "deprecated" directive:
1 argument(s) required, 0 supplied.

.. deprecated::
```

The user (who is a developer) can easily fix this problem in its own code.

**Comment by auscompgeek** [comment]
Problem is though if you specify a reason without a version, there's no warning; the first word is silently considered to be the version.
