### ISSUE TITLE
Using deprecated with C++ classes wrapped via pybind11

### ISSUE THREAD

**Issue by parejkoj** [tantale/deprecated#6]
We plan to use `deprecated` with our mixed C++/python codebase, including using it to decorate C++ functions and classes at the python level, so that python users see deprecation warnings (instead of just seeing them at compile time). However, there's an odd interaction between `pybind11` and `deprecated` when marking methods of classes as deprecated.

Pybind11-wrapped classes report the `type` of their methods as `<instanceMethod>`, not `<function>` in python. Thus the `deprecated` code at `classic.py:225` will register False and it will fall into the `else: raise TypeError()`. One possible solution to this would be for that `elif` on line 225 to read `elif inspect.isfunction(wrapped) or inspect.ismethod(wrapped):`. I'm not sure whether this is the best approach though.

@ktlim and @TallJimbo would be able to say more about the details of the pybind11 side of things.

LSST's deprecation guidelines are [online here](https://developer.lsst.io/stack/deprecating-interfaces.html#pybind11-deprecation), and the initial sketch of updates to that to support deprecating methods of classes is in [this PR](https://github.com/lsst-dm/dm_dev_guide/pull/308), which spawned this Issue.

**Comment by ktlim** [comment]
I think the most general test may be `inspect.isroutine(wrapped)`.

**Comment by laurent-laporte-pro** [comment]
Hi,

You are right, we ought to use [inspect.isroutine](https://docs.python.org/3/library/inspect.html#inspect.isroutine)

> inspect.**isroutine**(object)
>     Return true if the object is a user-defined or built-in function or method.

**Comment by parejkoj** [comment]
Should I issue a PR for that, or is one of the deprecated developers on it?

**Comment by tantale** [comment]
Working on it. Currently having some unit tests issues… Stay tuned.

**Comment by tantale** [comment]
New release v1.2.5 done.

**Comment by parejkoj** [comment]
Thank you!

**Comment by tantale** [comment]
You are welcome 😉. I you appreciate this project, you can star ★ it!
