### ISSUE TITLE
is there plans to release a 1.2.14 patch version ? 

### ISSUE THREAD

**Issue by 12rambau** [tantale/deprecated#65]
My PR (#61) was recently pushed to the repository, it's nothing fancy but it's solving an issue for anyone using the ruff linter with the docstring default parameter. As the ruff project is getting much attention maybe this could be integrated in a patch release to be available for pypi installation.

**Comment by tantale** [comment]
Fixed in https://github.com/tantale/deprecated/releases/tag/v1.2.14
