### ISSUE TITLE
is travis still in use ? 

### ISSUE THREAD

**Issue by 12rambau** [tantale/deprecated#66]
I was looking at the deprecated files and see there is a .travis.yml file. I remember last year that travis dropped support for open source repositories.  There is no travis badge in the readme so I was asking myself, is it still used ? 

If no would you be opened to move the test to a github action ?

**Comment by tantale** [comment]
Hi @12rambau,

Thank you for bringing up the issue regarding the outdated configuration files for Travis CI (and AppVeyor too) in the "Deprecated" project. After careful consideration, I agree that it's best to remove these obsolete files and use a GitHub Actions workflow for testing instead.

To achieve this, I propose the following changes:

1. Remove the [.travis.yml](https://github.com/tantale/deprecated/blob/master/.travis.yml) file.
2. Remove the [appveyor.yml](https://github.com/tantale/deprecated/blob/master/appveyor.yml) file.
3. Update the README file and/or the documentation to reflect the use of GitHub Actions for testing.

We already have a suitable GitHub Actions workflow file, [python-package.yml](https://github.com/tantale/deprecated/blob/master/.github/workflows/python-package.yml), which covers the necessary testing and compatibility requirements. This workflow can replace the outdated CI configurations effectively.

I kindly request you to open a pull request (PR) with these changes directly on the main branch of the "Deprecated" project.

Best regards,
– Laurent LAPORTE
